version: '3'
services:
  server:
    build: .
    command: npm test
    ports:
      - "5000:5000"
    depends_on:
    - redis
  redis:
    image: redis:3.2.0
    ports:
      - "6379:6379"
  stream:
    image: segment/fake-event-stream
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=events
      - EVENTS_PER_SECOND=100
    links:
      - redis
    